/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmanagement;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import static java.lang.ProcessBuilder.Redirect.to;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;

/**
 *
 * @author kani
 */
public class registerr extends javax.swing.JFrame {
    int OTP;

    /**
     * Creates new form registerr
     */
    public registerr() {
        initComponents();
        regname.setBackground(new java.awt.Color(0,0,0,1));
        regpassword.setBackground(new java.awt.Color(0,0,0,1));
        regphone.setBackground(new java.awt.Color(0,0,0,1));
        regotp.setBackground(new java.awt.Color(0,0,0,1));
    }

    registerr(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regname = new javax.swing.JTextField();
        regpassword = new javax.swing.JTextField();
        regphone = new javax.swing.JTextField();
        regotp = new javax.swing.JTextField();
        regotpbtn = new javax.swing.JButton();
        regloginbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        regbackbtn = new javax.swing.JButton();
        userlbl = new javax.swing.JLabel();
        passlbl = new javax.swing.JLabel();
        maillbl = new javax.swing.JLabel();
        otplbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        regname.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        regname.setForeground(new java.awt.Color(0, 255, 204));
        regname.setBorder(null);
        regname.setNextFocusableComponent(regpassword);
        regname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regnameMouseExited(evt);
            }
        });
        getContentPane().add(regname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 250, 40));

        regpassword.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        regpassword.setForeground(new java.awt.Color(0, 255, 204));
        regpassword.setBorder(null);
        regpassword.setNextFocusableComponent(regphone);
        regpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regpasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regpasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regpasswordMouseExited(evt);
            }
        });
        regpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(regpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 250, 40));

        regphone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        regphone.setForeground(new java.awt.Color(0, 0, 0));
        regphone.setBorder(null);
        regphone.setNextFocusableComponent(regotpbtn);
        regphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regphoneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regphoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regphoneMouseExited(evt);
            }
        });
        regphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regphoneActionPerformed(evt);
            }
        });
        getContentPane().add(regphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 280, 40));

        regotp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        regotp.setForeground(new java.awt.Color(0, 0, 0));
        regotp.setBorder(null);
        regotp.setNextFocusableComponent(regloginbtn);
        regotp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regotpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regotpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regotpMouseExited(evt);
            }
        });
        getContentPane().add(regotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, 80, 40));

        regotpbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regotpbtn.setForeground(new java.awt.Color(11, 212, 145));
        regotpbtn.setText("Get otp");
        regotpbtn.setContentAreaFilled(false);
        regotpbtn.setNextFocusableComponent(regotp);
        regotpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regotpbtnActionPerformed(evt);
            }
        });
        getContentPane().add(regotpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 430, -1, 20));

        regloginbtn.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        regloginbtn.setForeground(new java.awt.Color(21, 205, 144));
        regloginbtn.setText("Log In");
        regloginbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 3, true));
        regloginbtn.setContentAreaFilled(false);
        regloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regloginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(regloginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 530, 100, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif pic/leaf2 gif.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif pic/leaf gif.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif pic/leaf gif.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif pic/branch gif.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        regbackbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        regbackbtn.setForeground(new java.awt.Color(20, 163, 116));
        regbackbtn.setText("Back");
        regbackbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 3, true));
        regbackbtn.setContentAreaFilled(false);
        regbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(regbackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 80, 40));

        userlbl.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        userlbl.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(userlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 250, -1));

        passlbl.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        passlbl.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(passlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 250, -1));

        maillbl.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        maillbl.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(maillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 270, -1));

        otplbl.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        otplbl.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(otplbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registration.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regotpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regotpbtnActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();
        OTP = rand.nextInt(999999);
                        
        String fromgmail="kanidreamfruits@gmail.com";
        String togmail =regphone.getText();
        Properties props= new Properties();
        props.put("mail.smtp.auth","true");
        props.put("mail.smtp.starttls.enable","true");
        props.put("mail.smtp.host","smtp.gmail.com");
        props.put("mail.smtp.port",587);
        Session session = Session.getDefaultInstance(props,
            new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication(){
            return new PasswordAuthentication("kanidreamfruits@gmail.com","kani4321");
            } 
        });
        try{  
             MimeMessage message = new MimeMessage(session);  
             message.setFrom(new InternetAddress(fromgmail));  
             message.addRecipient(Message.RecipientType.TO,new InternetAddress(togmail));  
             message.setSubject("KDF's VERIFICATION");  
             message.setText("Hello,this is your otp :"+OTP);  
             
             // Send message  
             Transport.send(message);
             System.out.println("message sent successfully....");  
             JOptionPane.showConfirmDialog(null,"Otp sent successfully");

          }catch (MessagingException mex) {
              JOptionPane.showConfirmDialog(null,"Something went wrong...\n please tryagain after sometimes");
              mex.printStackTrace();
          }    

    /*  
      String to = "dmani56as@gmail.com";//change accordingly  
      String from = "kanidreamfruits@gmail.com"; //change accordingly  
      String host = "localhost";//or IP address  
  
     //Get the session object  
      Properties properties = System.getProperties();  
      properties.setProperty("mail.smtp.host", host);  
      Session session = Session.getDefaultInstance(properties);  
  
     //compose the message  
      try{  
         MimeMessage message = new MimeMessage(session);  
         message.setFrom(new InternetAddress(from));  
         message.addRecipient(Message.RecipientType.TO,new InternetAddress(to));  
         message.setSubject("Ping");  
         message.setText("Hello, this is example of sending email  ");  
  
         // Send message  
         Transport.send(message);  
         System.out.println("message sent successfully....");  
  
      }catch (MessagingException mex) {
          mex.printStackTrace();
      }  
      */
        /*
        try {
			// Construct data
			String apiKey = "apikey=" + "71240CVYSmw-PiQguMayFKWmVXt2mjiBuBVcBQ3lUe";
                        Random rand = new Random();
                        OTP = rand.nextInt(999999);
                        String name =regname.getText();
                        
			String message = "&message=" + "Hello"+name+"your otp is"+OTP;
			String sender = "&sender=" + "TXTLCL";
			String numbers = "&numbers=" +"91 9994249808";
                        System.out.println(OTP);
                        System.out.println(message);
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = rd.readLine()) != null) {
				stringBuffer.append(line);
			}
			rd.close();
			JOptionPane.showConfirmDialog(null,"Otp sent successfully");
		} catch (Exception e) {
                        JOptionPane.showConfirmDialog(null,"Otp sent failed");
			System.out.println("Error SMS "+e);
		}
        */
    }//GEN-LAST:event_regotpbtnActionPerformed

    private void regloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regloginbtnActionPerformed
        // TODO add your handling code here:
        loginn login=new loginn();
        userlbl.setText("");
        passlbl.setText("");
        otplbl.setText("");
        if(regname.getText().trim().isEmpty() && regpassword.getText().trim().isEmpty()){
            userlbl.setText("name is Empty");
            passlbl.setText("password is Empty");
        }
        if(regname.getText().trim().isEmpty()){
            userlbl.setText("name is Empty");
        }
        if(regpassword.getText().trim().isEmpty()){
            passlbl.setText("password is Empty");
        }
        if(regotp.getText().trim().isEmpty()){
            otplbl.setText("enter valid otp");
        }
        System.out.println("otp is in login part:"+OTP);
        try{
        if(Integer.parseInt(regotp.getText())==OTP){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con =DriverManager.getConnection("jdbc:mysql://127.0.0.1/projectkani","root","");
                String sql = "INSERT INTO login_table2(username,password)VALUES(?,?)";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, regname.getText());
                pst.setString(2,regpassword.getText());
                pst.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(null,"Register successfully");
                dispose();
                login.setVisible(true);
                } 
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);

            }
        }
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,"Wrong Input"); 
        }
    }//GEN-LAST:event_regloginbtnActionPerformed

    private void regphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regphoneActionPerformed

    private void regbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbackbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        loginn login=new loginn();
        login.setVisible(true);
                
    }//GEN-LAST:event_regbackbtnActionPerformed

    private void regpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regpasswordActionPerformed

    private void regnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regnameMouseEntered
        // TODO add your handling code here:
        userlbl.setText("Enter name");
    }//GEN-LAST:event_regnameMouseEntered

    private void regnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regnameMouseClicked
        // TODO add your handling code here:
        userlbl.setText("");
    }//GEN-LAST:event_regnameMouseClicked

    private void regpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regpasswordMouseClicked
        // TODO add your handling code here:
        passlbl.setText("");
    }//GEN-LAST:event_regpasswordMouseClicked

    private void regphoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regphoneMouseEntered
        // TODO add your handling code here:
        maillbl.setText("Enter Gmail Address");
    }//GEN-LAST:event_regphoneMouseEntered

    private void regphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regphoneMouseClicked
        // TODO add your handling code here:
        maillbl.setText("");
    }//GEN-LAST:event_regphoneMouseClicked

    private void regpasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regpasswordMouseEntered
        // TODO add your handling code here:
        passlbl.setText("Enter Password");
    }//GEN-LAST:event_regpasswordMouseEntered

    private void regnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regnameMouseExited
        // TODO add your handling code here:
        userlbl.setText("");
    }//GEN-LAST:event_regnameMouseExited

    private void regpasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regpasswordMouseExited
        // TODO add your handling code here:
        passlbl.setText("");
    }//GEN-LAST:event_regpasswordMouseExited

    private void regphoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regphoneMouseExited
        // TODO add your handling code here:
        maillbl.setText("");
    }//GEN-LAST:event_regphoneMouseExited

    private void regotpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regotpMouseClicked
        // TODO add your handling code here:
        otplbl.setText("");
    }//GEN-LAST:event_regotpMouseClicked

    private void regotpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regotpMouseEntered
        // TODO add your handling code here:
        otplbl.setText("Enter OTP");
    }//GEN-LAST:event_regotpMouseEntered

    private void regotpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regotpMouseExited
        // TODO add your handling code here:
        otplbl.setText("");
    }//GEN-LAST:event_regotpMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel maillbl;
    private javax.swing.JLabel otplbl;
    private javax.swing.JLabel passlbl;
    private javax.swing.JButton regbackbtn;
    private javax.swing.JButton regloginbtn;
    private javax.swing.JTextField regname;
    private javax.swing.JTextField regotp;
    private javax.swing.JButton regotpbtn;
    private javax.swing.JTextField regpassword;
    private javax.swing.JTextField regphone;
    private javax.swing.JLabel userlbl;
    // End of variables declaration//GEN-END:variables
}
